version: '3'

services:
  bot:
    build: 
      context: bot
      dockerfile: Dockerfile
    depends_on:
      - postgres
    links:
      - postgres
    env_file:
      - .env
    volumes:
      - telegram_cli:/root/.telegram-cli:ro
    logging:
      options:
        max-size: 10m
    #restart: unless-stopped
  scan:
    build: 
      context: scan
      dockerfile: Dockerfile
    depends_on:
      - postgres
    links:
      - postgres
    env_file:
      - .env
    #command: ["python3"]
    logging:
      options:
        max-size: 10m
    #restart: unless-stopped
  digest:
    build: 
      context: digest
      dockerfile: Dockerfile
    depends_on:
      - postgres
    links:
      - postgres
    env_file:
      - .env
    logging:
      options:
        max-size: 10m
    restart: unless-stopped
  discord:
    build: 
      context: discord
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    depends_on:
      - postgres
    links:
      - postgres
    env_file:
      - .env
    logging:
      options:
        max-size: 10m
    restart: unless-stopped
  telegram:
    build: 
      context: telegram
      dockerfile: Dockerfile
    stdin_open: true
    depends_on:
      - postgres
    links:
      - postgres
    env_file:
      - .env
    restart: unless-stopped
    logging:
      options:
        max-size: 10m
    volumes:
      - telegram_cli:/root/.telegram-cli
  postgres:
    build: 
      context: postgres
      dockerfile: Dockerfile
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./postgres/:/docker-entrypoint-initdb.d/
    restart: unless-stopped
    env_file:
      - .env
    logging:
      options:
        max-size: 10m
volumes:
  postgres: {}
  telegram_cli: {}